### ISSUE TITLE
Unit tests for app/clients/coin-market-cap/client.go

### ISSUE THREAD

**Issue by ghost** [LimeChain/hashport-validator#421] opened 2022-03-08 11:54 UTC
- Implement unit tests for **app/clients/coin-market-cap/client.go**

**Comment by Psykepro** [comment] 2022-04-05 12:43
this ticket is duplicate of already closed one: https://app.zenhub.com/workspaces/hashport-bridge-5faa7a326bd8890015ff754d/issues/limechain/hashport-validator/507

**Closed** 2022-04-11 10:30 UTC
Labels: unit tests
